BEGIN;

CREATE SCHEMA IF NOT EXISTS metier;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace
    WHERE t.typname = 'role_utilisateur' AND n.nspname = 'metier'
  ) THEN
    CREATE TYPE metier.role_utilisateur AS ENUM ('etudiant', 'coach', 'psychologue', 'admin');
  END IF;
END$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace
    WHERE t.typname = 'statut_rdv' AND n.nspname = 'metier'
  ) THEN
    CREATE TYPE metier.statut_rdv AS ENUM ('en_attente', 'confirme', 'annule');
  END IF;
END$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace
    WHERE t.typname = 'type_discussion' AND n.nspname = 'metier'
  ) THEN
    CREATE TYPE metier.type_discussion AS ENUM ('texte', 'audio', 'video');
  END IF;
END$$;

CREATE TABLE IF NOT EXISTS metier.utilisateur (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  payload_user_id integer UNIQUE,
  nom_prenom varchar NOT NULL,
  login_email varchar NOT NULL UNIQUE,
  avatar text,
  role metier.role_utilisateur NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT utilisateur_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS metier.admin (
  id uuid NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT admin_pkey PRIMARY KEY (id),
  CONSTRAINT admin_id_fkey FOREIGN KEY (id) REFERENCES metier.utilisateur(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS metier.etudiant (
  id uuid NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT etudiant_pkey PRIMARY KEY (id),
  CONSTRAINT etudiant_id_fkey FOREIGN KEY (id) REFERENCES metier.utilisateur(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS metier.coach (
  id uuid NOT NULL,
  is_smart_coach boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT coach_pkey PRIMARY KEY (id),
  CONSTRAINT coach_id_fkey FOREIGN KEY (id) REFERENCES metier.utilisateur(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS metier.psychologue (
  id uuid NOT NULL,
  creneau_disponibilite jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT psychologue_pkey PRIMARY KEY (id),
  CONSTRAINT psychologue_id_fkey FOREIGN KEY (id) REFERENCES metier.utilisateur(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS metier.bien_etre (
  id_bien_etre bigint GENERATED BY DEFAULT AS IDENTITY,
  etudiant_id uuid NOT NULL UNIQUE,
  etat_critique boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT bien_etre_pkey PRIMARY KEY (id_bien_etre),
  CONSTRAINT bien_etre_etudiant_id_fkey FOREIGN KEY (etudiant_id) REFERENCES metier.etudiant(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS metier.detail_bien_etre (
  id_detail bigint GENERATED BY DEFAULT AS IDENTITY,
  bien_etre_id bigint NOT NULL,
  date date NOT NULL DEFAULT CURRENT_DATE,
  humeur varchar,
  sommeil varchar,
  stress varchar,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT detail_bien_etre_pkey PRIMARY KEY (id_detail),
  CONSTRAINT detail_bien_etre_bien_etre_id_fkey FOREIGN KEY (bien_etre_id) REFERENCES metier.bien_etre(id_bien_etre) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS metier.exercice (
  id_exercice bigint GENERATED BY DEFAULT AS IDENTITY,
  description text NOT NULL,
  check_in_etat boolean NOT NULL DEFAULT false,
  type_exercice varchar NOT NULL CHECK (type_exercice IN ('recommande_ia', 'post_seance', 'suivi_quotidien')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT exercice_pkey PRIMARY KEY (id_exercice)
);

CREATE TABLE IF NOT EXISTS metier.entretien (
  id_entretien bigint GENERATED BY DEFAULT AS IDENTITY,
  etudiant_id uuid NOT NULL,
  titre varchar NOT NULL,
  date date NOT NULL DEFAULT CURRENT_DATE,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT entretien_pkey PRIMARY KEY (id_entretien),
  CONSTRAINT entretien_etudiant_id_fkey FOREIGN KEY (etudiant_id) REFERENCES metier.etudiant(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS metier.question (
  id_question bigint GENERATED BY DEFAULT AS IDENTITY,
  entretien_id bigint NOT NULL,
  texte_quest text NOT NULL,
  type varchar NOT NULL CHECK (type IN ('chat', 'vocale')),
  categorie varchar,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT question_pkey PRIMARY KEY (id_question),
  CONSTRAINT question_entretien_id_fkey FOREIGN KEY (entretien_id) REFERENCES metier.entretien(id_entretien) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS metier.question_chat (
  id_question bigint NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT question_chat_pkey PRIMARY KEY (id_question),
  CONSTRAINT question_chat_id_question_fkey FOREIGN KEY (id_question) REFERENCES metier.question(id_question) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS metier.question_vocale (
  id_question bigint NOT NULL,
  url_audio text,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT question_vocale_pkey PRIMARY KEY (id_question),
  CONSTRAINT question_vocale_id_question_fkey FOREIGN KEY (id_question) REFERENCES metier.question(id_question) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS metier.reponse (
  id_reponse bigint GENERATED BY DEFAULT AS IDENTITY,
  question_id bigint NOT NULL UNIQUE,
  texte_reponse text NOT NULL,
  type varchar NOT NULL CHECK (type IN ('chat', 'vocale')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT reponse_pkey PRIMARY KEY (id_reponse),
  CONSTRAINT reponse_question_id_fkey FOREIGN KEY (question_id) REFERENCES metier.question(id_question) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS metier.reponse_chat (
  id_reponse bigint NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT reponse_chat_pkey PRIMARY KEY (id_reponse),
  CONSTRAINT reponse_chat_id_reponse_fkey FOREIGN KEY (id_reponse) REFERENCES metier.reponse(id_reponse) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS metier.reponse_vocale (
  id_reponse bigint NOT NULL,
  url_audio text,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT reponse_vocale_pkey PRIMARY KEY (id_reponse),
  CONSTRAINT reponse_vocale_id_reponse_fkey FOREIGN KEY (id_reponse) REFERENCES metier.reponse(id_reponse) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS metier.reve (
  ref_reve bigint GENERATED BY DEFAULT AS IDENTITY,
  etudiant_id uuid NOT NULL,
  date date NOT NULL DEFAULT CURRENT_DATE,
  etat_emotionnel varchar,
  description text NOT NULL,
  tag jsonb DEFAULT '[]'::jsonb,
  humeur varchar,
  intensite varchar,
  theme varchar,
  frequence varchar,
  video_status varchar NOT NULL DEFAULT 'pending',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT reve_pkey PRIMARY KEY (ref_reve),
  CONSTRAINT reve_etudiant_id_fkey FOREIGN KEY (etudiant_id) REFERENCES metier.etudiant(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS metier.video_ia_reve (
  id_video bigint GENERATED BY DEFAULT AS IDENTITY,
  reve_id bigint UNIQUE,
  url_video text NOT NULL,
  etat boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT video_ia_reve_pkey PRIMARY KEY (id_video),
  CONSTRAINT video_ia_reve_reve_id_fkey FOREIGN KEY (reve_id) REFERENCES metier.reve(ref_reve) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS metier.analyse_ai_personalite (
  id_analyse_pers bigint GENERATED BY DEFAULT AS IDENTITY,
  etudiant_id uuid NOT NULL,
  resume_personalite text,
  date date NOT NULL DEFAULT CURRENT_DATE,
  recommandations jsonb DEFAULT '[]'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT analyse_ai_personalite_pkey PRIMARY KEY (id_analyse_pers),
  CONSTRAINT analyse_ai_personalite_etudiant_id_fkey FOREIGN KEY (etudiant_id) REFERENCES metier.etudiant(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS metier.analyse_ai_reve (
  id_analyse_reve bigint GENERATED BY DEFAULT AS IDENTITY,
  reve_id bigint NOT NULL,
  resume_reve text,
  date date NOT NULL DEFAULT CURRENT_DATE,
  recommandations jsonb DEFAULT '[]'::jsonb,
  feedback_etudiant text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT analyse_ai_reve_pkey PRIMARY KEY (id_analyse_reve),
  CONSTRAINT analyse_ai_reve_reve_id_fkey FOREIGN KEY (reve_id) REFERENCES metier.reve(ref_reve) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS metier.exe_recommande_ia (
  id_exercice bigint NOT NULL,
  analyse_pers_id bigint,
  etudiant_id uuid,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT exe_recommande_ia_pkey PRIMARY KEY (id_exercice),
  CONSTRAINT exe_recommande_ia_id_exercice_fkey FOREIGN KEY (id_exercice) REFERENCES metier.exercice(id_exercice) ON DELETE CASCADE,
  CONSTRAINT exe_recommande_ia_analyse_pers_id_fkey FOREIGN KEY (analyse_pers_id) REFERENCES metier.analyse_ai_personalite(id_analyse_pers) ON DELETE SET NULL,
  CONSTRAINT exe_recommande_ia_etudiant_id_fkey FOREIGN KEY (etudiant_id) REFERENCES metier.etudiant(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS metier.suivi_quotidien (
  id_exercice bigint NOT NULL,
  etudiant_id uuid NOT NULL,
  date_suivi date NOT NULL DEFAULT CURRENT_DATE,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT suivi_quotidien_pkey PRIMARY KEY (id_exercice),
  CONSTRAINT suivi_quotidien_id_exercice_fkey FOREIGN KEY (id_exercice) REFERENCES metier.exercice(id_exercice) ON DELETE CASCADE,
  CONSTRAINT suivi_quotidien_etudiant_id_fkey FOREIGN KEY (etudiant_id) REFERENCES metier.etudiant(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS metier.seance (
  id_seance bigint GENERATED BY DEFAULT AS IDENTITY,
  coach_id uuid NOT NULL,
  date timestamptz NOT NULL,
  objectif text,
  lieu varchar,
  modalite varchar,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT seance_pkey PRIMARY KEY (id_seance),
  CONSTRAINT seance_coach_id_fkey FOREIGN KEY (coach_id) REFERENCES metier.coach(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS metier.detail_seance (
  seance_id bigint NOT NULL,
  etudiant_id uuid NOT NULL,
  role varchar,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT detail_seance_pkey PRIMARY KEY (seance_id, etudiant_id),
  CONSTRAINT detail_seance_seance_id_fkey FOREIGN KEY (seance_id) REFERENCES metier.seance(id_seance) ON DELETE CASCADE,
  CONSTRAINT detail_seance_etudiant_id_fkey FOREIGN KEY (etudiant_id) REFERENCES metier.etudiant(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS metier.exe_post_seance (
  id_exercice bigint NOT NULL,
  seance_id bigint NOT NULL,
  etudiant_id uuid NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT exe_post_seance_pkey PRIMARY KEY (id_exercice),
  CONSTRAINT exe_post_seance_id_exercice_fkey FOREIGN KEY (id_exercice) REFERENCES metier.exercice(id_exercice) ON DELETE CASCADE,
  CONSTRAINT exe_post_seance_seance_id_fkey FOREIGN KEY (seance_id) REFERENCES metier.seance(id_seance) ON DELETE CASCADE,
  CONSTRAINT exe_post_seance_etudiant_id_fkey FOREIGN KEY (etudiant_id) REFERENCES metier.etudiant(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS metier.annonce_motivation (
  id_annonce bigint GENERATED BY DEFAULT AS IDENTITY,
  coach_id uuid NOT NULL,
  date date NOT NULL DEFAULT CURRENT_DATE,
  titre varchar NOT NULL,
  motivation_corps text NOT NULL,
  audience varchar NOT NULL DEFAULT 'all_student',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT annonce_motivation_pkey PRIMARY KEY (id_annonce),
  CONSTRAINT annonce_motivation_coach_id_fkey FOREIGN KEY (coach_id) REFERENCES metier.coach(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS metier.discussion (
  id_discussion bigint GENERATED BY DEFAULT AS IDENTITY,
  etudiant_id uuid NOT NULL,
  coach_id uuid NOT NULL,
  object_disc varchar,
  date timestamptz NOT NULL DEFAULT now(),
  type metier.type_discussion NOT NULL DEFAULT 'texte',
  coach_note text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT discussion_pkey PRIMARY KEY (id_discussion),
  CONSTRAINT discussion_etudiant_id_fkey FOREIGN KEY (etudiant_id) REFERENCES metier.etudiant(id) ON DELETE CASCADE,
  CONSTRAINT discussion_coach_id_fkey FOREIGN KEY (coach_id) REFERENCES metier.coach(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS metier.demande_rendez_vous (
  id_dmd_rdv bigint GENERATED BY DEFAULT AS IDENTITY,
  etudiant_id uuid NOT NULL,
  psychologue_id uuid NOT NULL,
  date timestamptz NOT NULL,
  lieu varchar,
  modalite_rdv varchar,
  statut metier.statut_rdv NOT NULL DEFAULT 'en_attente',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT demande_rendez_vous_pkey PRIMARY KEY (id_dmd_rdv),
  CONSTRAINT demande_rendez_vous_etudiant_id_fkey FOREIGN KEY (etudiant_id) REFERENCES metier.etudiant(id) ON DELETE CASCADE,
  CONSTRAINT demande_rendez_vous_psychologue_id_fkey FOREIGN KEY (psychologue_id) REFERENCES metier.psychologue(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS metier.rdv_annule (
  id_dmd_rdv bigint NOT NULL,
  cause text,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT rdv_annule_pkey PRIMARY KEY (id_dmd_rdv),
  CONSTRAINT rdv_annule_id_dmd_rdv_fkey FOREIGN KEY (id_dmd_rdv) REFERENCES metier.demande_rendez_vous(id_dmd_rdv) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS metier.rdv_confirme (
  id_dmd_rdv bigint NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT rdv_confirme_pkey PRIMARY KEY (id_dmd_rdv),
  CONSTRAINT rdv_confirme_id_dmd_rdv_fkey FOREIGN KEY (id_dmd_rdv) REFERENCES metier.demande_rendez_vous(id_dmd_rdv) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_metier_utilisateur_email ON metier.utilisateur(login_email);
CREATE INDEX IF NOT EXISTS idx_metier_utilisateur_payload_user_id ON metier.utilisateur(payload_user_id);
CREATE INDEX IF NOT EXISTS idx_metier_reve_etudiant_id ON metier.reve(etudiant_id);
CREATE INDEX IF NOT EXISTS idx_metier_entretien_etudiant_id ON metier.entretien(etudiant_id);
CREATE INDEX IF NOT EXISTS idx_metier_question_entretien_id ON metier.question(entretien_id);
CREATE INDEX IF NOT EXISTS idx_metier_reponse_question_id ON metier.reponse(question_id);
CREATE INDEX IF NOT EXISTS idx_metier_rdv_etudiant_id ON metier.demande_rendez_vous(etudiant_id);
CREATE INDEX IF NOT EXISTS idx_metier_rdv_psychologue_id ON metier.demande_rendez_vous(psychologue_id);

COMMIT;
