/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    users: User;
    media: Media;
    'analyse-personnalite': AnalysePersonnalite;
    dreams: Dream;
    'coaching-sessions': CoachingSession;
    'coaching-messages': CoachingMessage;
    'coach-notes': CoachNote;
    'psy-availabilities': PsyAvailability;
    'rendez-vous-psy': RendezVousPsy;
    notifications: Notification;
    'annonce-motivation': AnnonceMotivation;
    'annonce-motivation-reactions': AnnonceMotivationReaction;
    'coaching-events': CoachingEvent;
    'coaching-registrations': CoachingRegistration;
    'psy-orientations': PsyOrientation;
    'student-exercices': StudentExercice;
    redirects: Redirect;
    forms: Form;
    'form-submissions': FormSubmission;
    search: Search;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'analyse-personnalite': AnalysePersonnaliteSelect<false> | AnalysePersonnaliteSelect<true>;
    dreams: DreamsSelect<false> | DreamsSelect<true>;
    'coaching-sessions': CoachingSessionsSelect<false> | CoachingSessionsSelect<true>;
    'coaching-messages': CoachingMessagesSelect<false> | CoachingMessagesSelect<true>;
    'coach-notes': CoachNotesSelect<false> | CoachNotesSelect<true>;
    'psy-availabilities': PsyAvailabilitiesSelect<false> | PsyAvailabilitiesSelect<true>;
    'rendez-vous-psy': RendezVousPsySelect<false> | RendezVousPsySelect<true>;
    notifications: NotificationsSelect<false> | NotificationsSelect<true>;
    'annonce-motivation': AnnonceMotivationSelect<false> | AnnonceMotivationSelect<true>;
    'annonce-motivation-reactions': AnnonceMotivationReactionsSelect<false> | AnnonceMotivationReactionsSelect<true>;
    'coaching-events': CoachingEventsSelect<false> | CoachingEventsSelect<true>;
    'coaching-registrations': CoachingRegistrationsSelect<false> | CoachingRegistrationsSelect<true>;
    'psy-orientations': PsyOrientationsSelect<false> | PsyOrientationsSelect<true>;
    'student-exercices': StudentExercicesSelect<false> | StudentExercicesSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  layout: (
    | {
        title?: string | null;
        subtitle?: string | null;
        emailPlaceholder?: string | null;
        passwordPlaceholder?: string | null;
        buttonLabel?: string | null;
        signupText?: string | null;
        signupLabel?: string | null;
        signupUrl?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'loginBlock';
      }
    | CallToActionBlock
    | ContentBlock
    | MediaBlock
    | ArchiveBlock
    | FormBlock
    | {
        title: string;
        description: string;
        primaryButton: {
          label: string;
          href: string;
        };
        secondaryButton?: {
          label?: string | null;
          href?: string | null;
        };
        badges?:
          | {
              label: string;
              id?: string | null;
            }[]
          | null;
        mockupTitle?: string | null;
        mockupMessage?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'landingHero';
      }
    | {
        title: string;
        features: {
          icon: 'moon' | 'sparkles' | 'messageCircle';
          title: string;
          description: string;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'secondBlocAccueil';
      }
    | {
        title: string;
        features: {
          icon: 'brain' | 'bot' | 'messageCircle' | 'clock' | 'heartHandshake' | 'video';
          label: string;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'troisiemeBlocAccueil';
      }
    | {
        title: string;
        steps: {
          icon: 'userPlus' | 'bot' | 'bookOpen';
          title: string;
          description: string;
          id?: string | null;
        }[];
        testimonialName: string;
        testimonialRole: string;
        testimonialText: string;
        rating: number;
        id?: string | null;
        blockName?: string | null;
        blockType: 'quatriemeBlocAccueil';
      }
    | {
        title: string;
        testimonials: {
          name: string;
          role: string;
          review: string;
          rating: number;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'cinquiemeBlocAccueil';
      }
    | {
        title: string;
        subtitle?: string | null;
        cards?:
          | {
              title: string;
              description: string;
              icon?: (number | null) | Media;
              link: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'roleCards';
      }
    | {
        id?: string | null;
        blockName?: string | null;
        blockType: 'accompagnementHero';
      }
    | {
        id?: string | null;
        blockName?: string | null;
        blockType: 'accompagnementStress';
      }
    | {
        id?: string | null;
        blockName?: string | null;
        blockType: 'accompagnementProcess';
      }
    | {
        id?: string | null;
        blockName?: string | null;
        blockType: 'aboutHero';
      }
    | {
        id?: string | null;
        blockName?: string | null;
        blockType: 'aboutTeam';
      }
    | {
        id?: string | null;
        blockName?: string | null;
        blockType: 'aboutEthics';
      }
    | {
        id?: string | null;
        blockName?: string | null;
        blockType: 'aboutVision';
      }
    | {
        brand: string;
        titleFr: string;
        titleEn: string;
        descriptionFr: string;
        descriptionEn: string;
        stats?:
          | {
              icon: 'sparkles' | 'shieldCheck' | 'star' | 'users';
              value: string;
              labelFr: string;
              labelEn: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'contactHero';
      }
    | {
        emailsTitleFr: string;
        emailsTitleEn: string;
        emails?:
          | {
              icon: 'mail' | 'lifebuoy' | 'handshake';
              tagFr: string;
              tagEn: string;
              address: string;
              descFr: string;
              descEn: string;
              id?: string | null;
            }[]
          | null;
        teamTextFr: string;
        teamTextEn: string;
        teamAvatars?:
          | {
              initials: string;
              id?: string | null;
            }[]
          | null;
        faqTitleFr: string;
        faqTitleEn: string;
        faqItems?:
          | {
              qFr: string;
              qEn: string;
              aFr: string;
              aEn: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'contactContent';
      }
    | {
        id?: string | null;
        blockName?: string | null;
        blockType: 'featuresHero';
      }
    | {
        id?: string | null;
        blockName?: string | null;
        blockType: 'featuresTabs';
      }
    | {
        id?: string | null;
        blockName?: string | null;
        blockType: 'featureHighlight';
      }
    | {
        id?: string | null;
        blockName?: string | null;
        blockType: 'nutrition';
      }
  )[];
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  publishedAt?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: number | Page;
          } | null;
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  columns?:
    | {
        size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
        richText?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: number | Page;
          } | null;
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock".
 */
export interface ArchiveBlock {
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  populateBy?: ('collection' | 'selection') | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'pages';
        value: number | Page;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'archive';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  form: number | Form;
  enableIntro?: boolean | null;
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  owner?: (number | null) | User;
  dream?: (number | null) | Dream;
  sourceUrl?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  clerkUserId?: string | null;
  magic_login_token?: string | null;
  magic_login_expires_at?: string | null;
  firstName?: string | null;
  lastName?: string | null;
  studentBranch?: ('LI' | 'LEA' | 'LPE' | 'PC' | 'MP' | 'LM' | 'LSE' | 'master') | null;
  studentLevel?:
    | (
        | 'MP1'
        | 'MP2'
        | 'PC1'
        | 'PC2'
        | 'LMI1'
        | 'LMI2'
        | 'LMI3'
        | 'LI1'
        | 'LI2'
        | 'LI3'
        | 'LEA1'
        | 'LEE2'
        | 'LEE3'
        | 'LSE1'
        | 'LSE2'
        | 'LSE3'
        | 'LPE1'
        | 'LPE2'
        | 'LPE3'
        | 'MR1PHY'
        | 'MP1IASER'
        | 'MP1BIO'
        | 'MR1MATH'
      )
    | null;
  onboardingStep: 'profile' | 'interview' | 'completed';
  role: 'admin' | 'etudiant' | 'coach' | 'psy';
  /**
   * Activez ce champ quand le coach peut recevoir de nouvelles sessions d'accompagnement.
   */
  isAvailableForCoaching?: boolean | null;
  /**
   * Exemple : stress, motivation, orientation, organisation.
   */
  coachingSpecialty?: string | null;
  coachingBio?: string | null;
  /**
   * Derniers traits Big Five enregistres automatiquement apres l'entretien de personnalite.
   */
  bigFiveProfile?: {
    analysisId?: number | null;
    date?: string | null;
    traits?:
      | {
          name: 'Ouverture' | 'Conscienciosite' | 'Extraversion' | 'Agreabilite' | 'Neuroticisme';
          score: number;
          confidence?: ('eleve' | 'moyen' | 'faible') | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dreams".
 */
export interface Dream {
  id: number;
  user: number | User;
  description: string;
  summary?: string | null;
  analysis?: string | null;
  videoStatus: 'pending' | 'waiting_validation' | 'generating' | 'ready' | 'failed';
  videoUrl?: string | null;
  videoAsset?: (number | null) | Media;
  operationName?: string | null;
  errorMessage?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analyse-personnalite".
 */
export interface AnalysePersonnalite {
  id: number;
  /**
   * Reference unique de l analyse
   */
  reference: string;
  user: number | User;
  date: string;
  niveauConfiance?: ('eleve' | 'moyen' | 'modere') | null;
  sessionId?: string | null;
  /**
   * Historique complet de la conversation
   */
  conversation?:
    | {
        role: 'ai' | 'human';
        message: string;
        time?: string | null;
        emotion?:
          | ('joie' | 'anxiete' | 'neutre' | 'frustration' | 'hesitation' | 'confiance' | 'tristesse' | 'enthousiasme')
          | null;
        emotionScore?: number | null;
        source?: ('text' | 'voice') | null;
        id?: string | null;
      }[]
    | null;
  traits?:
    | {
        name: 'Ouverture' | 'Conscienciosite' | 'Extraversion' | 'Agreabilite' | 'Neuroticisme';
        score: number;
        analysis?: string | null;
        interpretation?: string | null;
        confidence?: ('eleve' | 'moyen' | 'faible') | null;
        confidenceReason?: string | null;
        observedIndicators?:
          | {
              indicator?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  profilEmotionnel?: {
    dominantEmotion?: string | null;
    emotionalStability?: number | null;
    emotionalSummary?: string | null;
  };
  overview?: string | null;
  forcesDominantes?: string | null;
  pointsVigilance?: string | null;
  styleRelationnel?: string | null;
  recommandations?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  conclusion?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coaching-sessions".
 */
export interface CoachingSession {
  id: number;
  title: string;
  student: number | User;
  coach?: (number | null) | User;
  mode: 'smart' | 'classic';
  status: 'open' | 'closed';
  startedAt: string;
  endedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coaching-messages".
 */
export interface CoachingMessage {
  id: number;
  session: number | CoachingSession;
  senderRole: 'student' | 'coach' | 'ai';
  senderUser?: (number | null) | User;
  content: string;
  audioUrl?: string | null;
  transcription?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coach-notes".
 */
export interface CoachNote {
  id: number;
  title: string;
  session: number | CoachingSession;
  student: number | User;
  coach: number | User;
  content: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "psy-availabilities".
 */
export interface PsyAvailability {
  id: number;
  label: string;
  psychologist: number | User;
  dayOfWeek: 'monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday' | 'sunday';
  /**
   * Format HH:mm, exemple 09:00
   */
  startTime: string;
  /**
   * Format HH:mm, exemple 12:00
   */
  endTime: string;
  slotDuration: number;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rendez-vous-psy".
 */
export interface RendezVousPsy {
  id: number;
  title: string;
  student: number | User;
  psychologist: number | User;
  /**
   * Renseigne si ce rendez-vous vient d'une orientation creee par un coach.
   */
  orientation?: (number | null) | PsyOrientation;
  date: string;
  startTime: string;
  endTime: string;
  reason: string;
  urgency: 'normal' | 'urgent';
  status: 'pending' | 'confirmed' | 'rejected' | 'cancelled' | 'completed';
  /**
   * Expliquez pourquoi le rendez-vous est refuse afin d'orienter l'etudiant.
   */
  rejectionReason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "psy-orientations".
 */
export interface PsyOrientation {
  id: number;
  title: string;
  student: number | User;
  coach: number | User;
  reason: string;
  observation?: string | null;
  status: 'pending_student_response' | 'student_refused' | 'student_accepted' | 'appointment_requested' | 'cancelled';
  studentRefusalReason?: string | null;
  studentRespondedAt?: string | null;
  appointment?: (number | null) | RendezVousPsy;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications".
 */
export interface Notification {
  id: number;
  recipient: number | User;
  actor?: (number | null) | User;
  title: string;
  message: string;
  type: 'rendezvous' | 'coaching' | 'analyse' | 'motivation' | 'system';
  status: 'unread' | 'read';
  link?: string | null;
  sendEmail?: boolean | null;
  emailStatus: 'skipped' | 'pending' | 'sent' | 'failed';
  readAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "annonce-motivation".
 */
export interface AnnonceMotivation {
  id: number;
  title: string;
  content: string;
  author: number | User;
  status: 'draft' | 'published';
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "annonce-motivation-reactions".
 */
export interface AnnonceMotivationReaction {
  id: number;
  announcement: number | AnnonceMotivation;
  student: number | User;
  reaction: 'like';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coaching-events".
 */
export interface CoachingEvent {
  id: number;
  title: string;
  theme: string;
  description: string;
  coach: number | User;
  scheduledAt: string;
  durationMinutes: number;
  teamsJoinUrl?: string | null;
  status: 'draft' | 'published' | 'cancelled' | 'completed';
  announcementSentAt?: string | null;
  reminderSentAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coaching-registrations".
 */
export interface CoachingRegistration {
  id: number;
  event: number | CoachingEvent;
  student: number | User;
  motivation: string;
  questions?: string | null;
  specialNeeds?: string | null;
  status: 'registered' | 'cancelled';
  registeredAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "student-exercices".
 */
export interface StudentExercice {
  id: number;
  title: string;
  instructions: string;
  student: number | User;
  coach: number | User;
  reason?: string | null;
  status: 'assigned' | 'in_progress' | 'completed' | 'reviewed' | 'missed';
  dueDate?: string | null;
  studentResponse?: string | null;
  coachFeedback?: string | null;
  assignedAt: string;
  completedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * You will need to rebuild the website when changing this field.
   */
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?: {
      relationTo: 'pages';
      value: number | Page;
    } | null;
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: number;
  title?: string | null;
  priority?: number | null;
  doc: {
    relationTo: 'pages';
    value: number | Page;
  };
  slug?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  categories?:
    | {
        relationTo?: string | null;
        categoryID?: string | null;
        title?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'analyse-personnalite';
        value: number | AnalysePersonnalite;
      } | null)
    | ({
        relationTo: 'dreams';
        value: number | Dream;
      } | null)
    | ({
        relationTo: 'coaching-sessions';
        value: number | CoachingSession;
      } | null)
    | ({
        relationTo: 'coaching-messages';
        value: number | CoachingMessage;
      } | null)
    | ({
        relationTo: 'coach-notes';
        value: number | CoachNote;
      } | null)
    | ({
        relationTo: 'psy-availabilities';
        value: number | PsyAvailability;
      } | null)
    | ({
        relationTo: 'rendez-vous-psy';
        value: number | RendezVousPsy;
      } | null)
    | ({
        relationTo: 'notifications';
        value: number | Notification;
      } | null)
    | ({
        relationTo: 'annonce-motivation';
        value: number | AnnonceMotivation;
      } | null)
    | ({
        relationTo: 'annonce-motivation-reactions';
        value: number | AnnonceMotivationReaction;
      } | null)
    | ({
        relationTo: 'coaching-events';
        value: number | CoachingEvent;
      } | null)
    | ({
        relationTo: 'coaching-registrations';
        value: number | CoachingRegistration;
      } | null)
    | ({
        relationTo: 'psy-orientations';
        value: number | PsyOrientation;
      } | null)
    | ({
        relationTo: 'student-exercices';
        value: number | StudentExercice;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'search';
        value: number | Search;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  layout?:
    | T
    | {
        loginBlock?:
          | T
          | {
              title?: T;
              subtitle?: T;
              emailPlaceholder?: T;
              passwordPlaceholder?: T;
              buttonLabel?: T;
              signupText?: T;
              signupLabel?: T;
              signupUrl?: T;
              id?: T;
              blockName?: T;
            };
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        archive?: T | ArchiveBlockSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
        landingHero?:
          | T
          | {
              title?: T;
              description?: T;
              primaryButton?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              secondaryButton?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              badges?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
              mockupTitle?: T;
              mockupMessage?: T;
              id?: T;
              blockName?: T;
            };
        secondBlocAccueil?:
          | T
          | {
              title?: T;
              features?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        troisiemeBlocAccueil?:
          | T
          | {
              title?: T;
              features?:
                | T
                | {
                    icon?: T;
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        quatriemeBlocAccueil?:
          | T
          | {
              title?: T;
              steps?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              testimonialName?: T;
              testimonialRole?: T;
              testimonialText?: T;
              rating?: T;
              id?: T;
              blockName?: T;
            };
        cinquiemeBlocAccueil?:
          | T
          | {
              title?: T;
              testimonials?:
                | T
                | {
                    name?: T;
                    role?: T;
                    review?: T;
                    rating?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        roleCards?:
          | T
          | {
              title?: T;
              subtitle?: T;
              cards?:
                | T
                | {
                    title?: T;
                    description?: T;
                    icon?: T;
                    link?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        accompagnementHero?:
          | T
          | {
              id?: T;
              blockName?: T;
            };
        accompagnementStress?:
          | T
          | {
              id?: T;
              blockName?: T;
            };
        accompagnementProcess?:
          | T
          | {
              id?: T;
              blockName?: T;
            };
        aboutHero?:
          | T
          | {
              id?: T;
              blockName?: T;
            };
        aboutTeam?:
          | T
          | {
              id?: T;
              blockName?: T;
            };
        aboutEthics?:
          | T
          | {
              id?: T;
              blockName?: T;
            };
        aboutVision?:
          | T
          | {
              id?: T;
              blockName?: T;
            };
        contactHero?:
          | T
          | {
              brand?: T;
              titleFr?: T;
              titleEn?: T;
              descriptionFr?: T;
              descriptionEn?: T;
              stats?:
                | T
                | {
                    icon?: T;
                    value?: T;
                    labelFr?: T;
                    labelEn?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        contactContent?:
          | T
          | {
              emailsTitleFr?: T;
              emailsTitleEn?: T;
              emails?:
                | T
                | {
                    icon?: T;
                    tagFr?: T;
                    tagEn?: T;
                    address?: T;
                    descFr?: T;
                    descEn?: T;
                    id?: T;
                  };
              teamTextFr?: T;
              teamTextEn?: T;
              teamAvatars?:
                | T
                | {
                    initials?: T;
                    id?: T;
                  };
              faqTitleFr?: T;
              faqTitleEn?: T;
              faqItems?:
                | T
                | {
                    qFr?: T;
                    qEn?: T;
                    aFr?: T;
                    aEn?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        featuresHero?:
          | T
          | {
              id?: T;
              blockName?: T;
            };
        featuresTabs?:
          | T
          | {
              id?: T;
              blockName?: T;
            };
        featureHighlight?:
          | T
          | {
              id?: T;
              blockName?: T;
            };
        nutrition?:
          | T
          | {
              id?: T;
              blockName?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  publishedAt?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  richText?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        size?: T;
        richText?: T;
        enableLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock_select".
 */
export interface ArchiveBlockSelect<T extends boolean = true> {
  introContent?: T;
  populateBy?: T;
  limit?: T;
  selectedDocs?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock_select".
 */
export interface FormBlockSelect<T extends boolean = true> {
  form?: T;
  enableIntro?: T;
  introContent?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  clerkUserId?: T;
  magic_login_token?: T;
  magic_login_expires_at?: T;
  firstName?: T;
  lastName?: T;
  studentBranch?: T;
  studentLevel?: T;
  onboardingStep?: T;
  role?: T;
  isAvailableForCoaching?: T;
  coachingSpecialty?: T;
  coachingBio?: T;
  bigFiveProfile?:
    | T
    | {
        analysisId?: T;
        date?: T;
        traits?:
          | T
          | {
              name?: T;
              score?: T;
              confidence?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  owner?: T;
  dream?: T;
  sourceUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analyse-personnalite_select".
 */
export interface AnalysePersonnaliteSelect<T extends boolean = true> {
  reference?: T;
  user?: T;
  date?: T;
  niveauConfiance?: T;
  sessionId?: T;
  conversation?:
    | T
    | {
        role?: T;
        message?: T;
        time?: T;
        emotion?: T;
        emotionScore?: T;
        source?: T;
        id?: T;
      };
  traits?:
    | T
    | {
        name?: T;
        score?: T;
        analysis?: T;
        interpretation?: T;
        confidence?: T;
        confidenceReason?: T;
        observedIndicators?:
          | T
          | {
              indicator?: T;
              id?: T;
            };
        id?: T;
      };
  profilEmotionnel?:
    | T
    | {
        dominantEmotion?: T;
        emotionalStability?: T;
        emotionalSummary?: T;
      };
  overview?: T;
  forcesDominantes?: T;
  pointsVigilance?: T;
  styleRelationnel?: T;
  recommandations?:
    | T
    | {
        text?: T;
        id?: T;
      };
  conclusion?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dreams_select".
 */
export interface DreamsSelect<T extends boolean = true> {
  user?: T;
  description?: T;
  summary?: T;
  analysis?: T;
  videoStatus?: T;
  videoUrl?: T;
  videoAsset?: T;
  operationName?: T;
  errorMessage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coaching-sessions_select".
 */
export interface CoachingSessionsSelect<T extends boolean = true> {
  title?: T;
  student?: T;
  coach?: T;
  mode?: T;
  status?: T;
  startedAt?: T;
  endedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coaching-messages_select".
 */
export interface CoachingMessagesSelect<T extends boolean = true> {
  session?: T;
  senderRole?: T;
  senderUser?: T;
  content?: T;
  audioUrl?: T;
  transcription?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coach-notes_select".
 */
export interface CoachNotesSelect<T extends boolean = true> {
  title?: T;
  session?: T;
  student?: T;
  coach?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "psy-availabilities_select".
 */
export interface PsyAvailabilitiesSelect<T extends boolean = true> {
  label?: T;
  psychologist?: T;
  dayOfWeek?: T;
  startTime?: T;
  endTime?: T;
  slotDuration?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rendez-vous-psy_select".
 */
export interface RendezVousPsySelect<T extends boolean = true> {
  title?: T;
  student?: T;
  psychologist?: T;
  orientation?: T;
  date?: T;
  startTime?: T;
  endTime?: T;
  reason?: T;
  urgency?: T;
  status?: T;
  rejectionReason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications_select".
 */
export interface NotificationsSelect<T extends boolean = true> {
  recipient?: T;
  actor?: T;
  title?: T;
  message?: T;
  type?: T;
  status?: T;
  link?: T;
  sendEmail?: T;
  emailStatus?: T;
  readAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "annonce-motivation_select".
 */
export interface AnnonceMotivationSelect<T extends boolean = true> {
  title?: T;
  content?: T;
  author?: T;
  status?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "annonce-motivation-reactions_select".
 */
export interface AnnonceMotivationReactionsSelect<T extends boolean = true> {
  announcement?: T;
  student?: T;
  reaction?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coaching-events_select".
 */
export interface CoachingEventsSelect<T extends boolean = true> {
  title?: T;
  theme?: T;
  description?: T;
  coach?: T;
  scheduledAt?: T;
  durationMinutes?: T;
  teamsJoinUrl?: T;
  status?: T;
  announcementSentAt?: T;
  reminderSentAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coaching-registrations_select".
 */
export interface CoachingRegistrationsSelect<T extends boolean = true> {
  event?: T;
  student?: T;
  motivation?: T;
  questions?: T;
  specialNeeds?: T;
  status?: T;
  registeredAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "psy-orientations_select".
 */
export interface PsyOrientationsSelect<T extends boolean = true> {
  title?: T;
  student?: T;
  coach?: T;
  reason?: T;
  observation?: T;
  status?: T;
  studentRefusalReason?: T;
  studentRespondedAt?: T;
  appointment?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "student-exercices_select".
 */
export interface StudentExercicesSelect<T extends boolean = true> {
  title?: T;
  instructions?: T;
  student?: T;
  coach?: T;
  reason?: T;
  status?: T;
  dueDate?: T;
  studentResponse?: T;
  coachFeedback?: T;
  assignedAt?: T;
  completedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  categories?:
    | T
    | {
        relationTo?: T;
        categoryID?: T;
        title?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: number | Page;
          } | null;
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: number | Page;
          } | null;
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?: {
      relationTo: 'pages';
      value: number | Page;
    } | null;
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}